# Generated by Django 4.1.5 on 2023-01-07 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('salads', 'salads'), ('appetizers', 'appetizers'), ('soups', 'soups'), ('main course', 'main course'), ('dessert', 'dessert')], default='salads', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Ingredients')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('slug', models.SlugField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='api.category')),
            ],
        ),
    ]
