# Generated by Django 4.1.5 on 2023-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cat_name_category_name_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SALADS', 'SALADS'), ('APPETIZERS', 'APPETIZERS'), ('SOUPS', 'SOUPS'), ('MAIN COURSE', 'MAIN COURSE'), ('DESSERT', 'DESSERT')], default='SALADS', max_length=20),
        ),
    ]
