# Generated by Django 4.1.5 on 2023-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('САЛАТЫ', 'САЛАТЫ'), ('ЗАКУСКИ', 'ЗАКУСКИ'), ('СУПЫ', 'СУПЫ'), ('ГОРЯЧЕЕ', 'ГОРЯЧЕЕ'), ('ДЕСЕРТЫ', 'ДЕСЕРТЫ')], default='САЛАТЫ', max_length=20),
        ),
    ]
